# Topsis

In [1]:
# importing libraries
# we use numpy, pandas, and math
import pandas as pd
import numpy as np
import math as m

In [2]:
#importing dataset for fault diagnosis from sensor
reqmt = pd.read_excel('./dataset/need_maintenance.xlsx')

In [3]:
# importing dataset
# this dataset containing all information that we need in this program
dataset = pd.read_excel('./dataset/dataset_workshop.xlsx') 
dataset.head()

workshop_name workshop_province workshop_city  \
0  Swiss-Belinn Tunjungan Surabaya        Jawa Timur      Surabaya   
1        Zoom Dharmahusada bengkel        Jawa Timur      Surabaya   
2          bengkel Gunawangsa MERR        Jawa Timur      Surabaya   
3                  Andalus bengkel        Jawa Timur      Surabaya   
4         Horison Arcadia Surabaya        Jawa Timur      Surabaya   

                                    workshop_address  distance  Rating  \
0          Jl. Tunjungan No.101, Surabaya, Indonesia      3160       2   
1  Jl. Raya Dharmahusada No. 188, Surabaya, Indon...      2690       1   
2  Jl. Kedung Baruk No. 96, Surabaya, Jawa Timur,...      1790       5   
3  Jl. Sultan Iskandar Muda No. 65, Ampel, Suraba...      3640       1   
4         Jl. Rajawali No. 9-11, Surabaya, Indonesia      3660       1   

   time_estimation    battery   brakepad      motor  
0       293.272727  Available  Available  Available  
1       249.545455  Available      Empty      Empty  
2       184.727273  Available  Available      Empty  
3       333.909091  Available  Available  Available  
4       344.727273  Available      Empty      Empty

In [4]:
#searh Avaibility with case need battery maintenance
if reqmt.iloc[0]['battery'] == 'FAIL':
    dataset = dataset[dataset['battery']== 'Available']
if reqmt.iloc[0]['brakepad'] == 'FAIL':
    dataset = dataset[dataset['brakepad']== 'Available']
if reqmt.iloc[0]['motor'] == 'FAIL':
    dataset = dataset[dataset['motor']== 'Available']
dataset = dataset.reset_index()
data = dataset 
#we will process the 'dataset', so so we back up the 'dataset' into 'data'
workshop = dataset['workshop_name']

In [5]:
dataset.head()

index                    workshop_name workshop_province workshop_city  \
0      0  Swiss-Belinn Tunjungan Surabaya        Jawa Timur      Surabaya   
1      1        Zoom Dharmahusada bengkel        Jawa Timur      Surabaya   
2      2          bengkel Gunawangsa MERR        Jawa Timur      Surabaya   
3      3                  Andalus bengkel        Jawa Timur      Surabaya   
4      4         Horison Arcadia Surabaya        Jawa Timur      Surabaya   

                                    workshop_address  distance  Rating  \
0          Jl. Tunjungan No.101, Surabaya, Indonesia      3160       2   
1  Jl. Raya Dharmahusada No. 188, Surabaya, Indon...      2690       1   
2  Jl. Kedung Baruk No. 96, Surabaya, Jawa Timur,...      1790       5   
3  Jl. Sultan Iskandar Muda No. 65, Ampel, Suraba...      3640       1   
4         Jl. Rajawali No. 9-11, Surabaya, Indonesia      3660       1   

   time_estimation    battery   brakepad      motor  
0       293.272727  Available  Available  Available  
1       249.545455  Available      Empty      Empty  
2       184.727273  Available  Available      Empty  
3       333.909091  Available  Available  Available  
4       344.727273  Available      Empty      Empty

In [34]:
#retrieve the measurement parameter
#we use distances, rating, and estimate time [collums 5,6,7]
dataset = dataset.iloc[:,5:8].values
row, col = dataset.shape
print(dataset)
print("Shape : {}x{}".format(row, col))


[[3.16000000e+03 2.00000000e+00 2.93272727e+02]
 [2.69000000e+03 1.00000000e+00 2.49545455e+02]
 [1.79000000e+03 5.00000000e+00 1.84727273e+02]
 [3.64000000e+03 1.00000000e+00 3.33909091e+02]
 [3.66000000e+03 1.00000000e+00 3.44727273e+02]
 [2.52000000e+03 4.00000000e+00 2.52090909e+02]
 [2.81000000e+03 2.00000000e+00 2.80454545e+02]
 [1.72000000e+03 4.00000000e+00 1.84363636e+02]
 [3.14000000e+03 4.00000000e+00 3.05454545e+02]
 [1.63000000e+03 1.00000000e+00 1.52181818e+02]
 [2.20000000e+03 5.00000000e+00 2.09000000e+02]
 [3.59000000e+03 5.00000000e+00 3.39363636e+02]
 [1.89000000e+03 3.00000000e+00 1.90818182e+02]
 [2.63000000e+03 3.00000000e+00 2.54090909e+02]
 [3.26000000e+03 5.00000000e+00 3.10363636e+02]
 [2.45000000e+03 4.00000000e+00 2.45727273e+02]
 [3.88000000e+03 2.00000000e+00 3.65727273e+02]
 [1.08000000e+03 2.00000000e+00 1.11181818e+02]
 [3.92000000e+03 1.00000000e+00 3.71363636e+02]
 [3.52000000e+03 4.00000000e+00 3.30000000e+02]
 [3.11000000e+03 3.00000000e+00 2.987272

In [35]:
# defining weights
# we setting weights value 30% for distance, 60% for ratings, and 10% for estimate time
w = [0.3, 0.6, 0.1]

In [36]:
# Step 1 => calculating normalized matrix
sumOfSquares = []
for j in range(0, col):
    sum = 0
    for i in range(0, row):
        value = dataset[i][j]
        sum = sum + m.pow(value,2)
    sqrtOfSum = m.sqrt(sum)
    sqrtOfSum = round(sqrtOfSum, 4)
    sumOfSquares.append(sqrtOfSum)
print('Column-wise root of sum of squares', sumOfSquares)

# creating a new 2D array
dataset2 = [[0 for i in range(col)] for j in range(row)] 

# dividing by the respected values
for j in range(0, col):
    for i in range(0, row):
        temp = dataset[i][j]/sumOfSquares[j]
        dataset2[i][j] = round(temp, 4)

print('normalized matrix')
print(np.matrix(dataset2))
normalized = pd.DataFrame(np.matrix(dataset2))
normalized.columns =['distance_normalized_matrix', 'rating_normalized_matrix', 'time_normalized_matrix'] 

Column-wise root of sum of squares [24526.3858, 28.9482, 2362.8621]
normalized matrix
[[0.1288 0.0691 0.1241]
 [0.1097 0.0345 0.1056]
 [0.073  0.1727 0.0782]
 [0.1484 0.0345 0.1413]
 [0.1492 0.0345 0.1459]
 [0.1027 0.1382 0.1067]
 [0.1146 0.0691 0.1187]
 [0.0701 0.1382 0.078 ]
 [0.128  0.1382 0.1293]
 [0.0665 0.0345 0.0644]
 [0.0897 0.1727 0.0885]
 [0.1464 0.1727 0.1436]
 [0.0771 0.1036 0.0808]
 [0.1072 0.1036 0.1075]
 [0.1329 0.1727 0.1314]
 [0.0999 0.1382 0.104 ]
 [0.1582 0.0691 0.1548]
 [0.044  0.0691 0.0471]
 [0.1598 0.0345 0.1572]
 [0.1435 0.1382 0.1397]
 [0.1268 0.1036 0.1264]
 [0.0416 0.1036 0.046 ]
 [0.0913 0.0345 0.0883]
 [0.1109 0.1036 0.1097]
 [0.1272 0.1727 0.1294]
 [0.1476 0.1036 0.1414]
 [0.1007 0.1382 0.1005]
 [0.0771 0.1382 0.0774]
 [0.1619 0.1727 0.1549]
 [0.0546 0.1382 0.0621]
 [0.1553 0.1382 0.1563]
 [0.0563 0.1382 0.0556]
 [0.0636 0.0691 0.0719]
 [0.0962 0.1036 0.0963]
 [0.1378 0.0345 0.1419]
 [0.0612 0.1727 0.067 ]
 [0.1468 0.0345 0.1482]
 [0.0734 0.1036 0.0794]
 [

In [37]:
# Step 2 => calculating weighted normalized matrix
for j in range(0, col):
    for i in range(0, row):
        temp2 = dataset2[i][j]*w[j]
        dataset2[i][j] = round(temp2, 4)
weighted = pd.DataFrame(np.matrix(dataset2))
weighted.columns =['distance_weighted_matrix', 'rating_weighted_matrix', 'time_weighted_matrix']
print('weighted normalized matrix')
print(np.matrix(dataset2))

weighted normalized matrix
[[0.0386 0.0415 0.0124]
 [0.0329 0.0207 0.0106]
 [0.0219 0.1036 0.0078]
 [0.0445 0.0207 0.0141]
 [0.0448 0.0207 0.0146]
 [0.0308 0.0829 0.0107]
 [0.0344 0.0415 0.0119]
 [0.021  0.0829 0.0078]
 [0.0384 0.0829 0.0129]
 [0.02   0.0207 0.0064]
 [0.0269 0.1036 0.0088]
 [0.0439 0.1036 0.0144]
 [0.0231 0.0622 0.0081]
 [0.0322 0.0622 0.0108]
 [0.0399 0.1036 0.0131]
 [0.03   0.0829 0.0104]
 [0.0475 0.0415 0.0155]
 [0.0132 0.0415 0.0047]
 [0.0479 0.0207 0.0157]
 [0.043  0.0829 0.014 ]
 [0.038  0.0622 0.0126]
 [0.0125 0.0622 0.0046]
 [0.0274 0.0207 0.0088]
 [0.0333 0.0622 0.011 ]
 [0.0382 0.1036 0.0129]
 [0.0443 0.0622 0.0141]
 [0.0302 0.0829 0.0101]
 [0.0231 0.0829 0.0077]
 [0.0486 0.1036 0.0155]
 [0.0164 0.0829 0.0062]
 [0.0466 0.0829 0.0156]
 [0.0169 0.0829 0.0056]
 [0.0191 0.0415 0.0072]
 [0.0289 0.0622 0.0096]
 [0.0413 0.0207 0.0142]
 [0.0184 0.1036 0.0067]
 [0.044  0.0207 0.0148]
 [0.022  0.0622 0.0079]
 [0.0253 0.1036 0.0083]
 [0.0187 0.0207 0.007 ]
 [0.0185 0.06

In [38]:
# Step 3 => calculating ideal best and ideal worst
# length of impacts should only increase if number of coulmns increase
impacts = ['-', '+', '-']
# as we know, the parameters for this scoring prosess are distances, rating, and estimate time
# the lower the ditances value, the better impact for the performance ('-')
# the higher the ditances rating, the better impact for the performance ('+')
# the lower the ditances estimate time, the better impact for the performance ('-')
bestValues = []
worstValues = []

dataset3 = pd.DataFrame(dataset2)
maxValues = dataset3.max()
minValues = dataset3.min()

for num in range(0, len(impacts)):
    if impacts[num] == '+':
        bestValues.append(maxValues[num])
        worstValues.append(minValues[num])
    else:
        bestValues.append(minValues[num])
        worstValues.append(maxValues[num])

# should only increase if number of columns increase
print('Ideal Best Values (r)\n', bestValues)
# print('')
print('Ideal Worst Values (r)\n', worstValues)

Ideal Best Values (r)
 [0.0125, 0.1036, 0.0046]
Ideal Worst Values (r)
 [0.0486, 0.0207, 0.0157]


In [39]:
# Step 4 => calculating euclidean distance from ideal bests and ideal worsts
SPlus = []
SMinus = []

# print(dataset2)

for i in range(0, row):
    bestSum = 0
    worstSum = 0
    for j in range(0, col):
        bestSum = bestSum + m.pow((dataset2[i][j]-bestValues[j]),2)
        worstSum = worstSum + m.pow((dataset2[i][j]-worstValues[j]), 2)
    SPlus.append(round(m.sqrt(bestSum), 4))
    SMinus.append(round(m.sqrt(worstSum), 4))
    
# should only increase if number of rows increase
plus_impact = pd.DataFrame(SPlus)
min_impact = pd.DataFrame(SMinus)
plus_impact.columns =['plus_impact']
min_impact.columns =['min_impact']
print('SPlus (c)\n', SPlus)
# print('')
print('SMinus (c)\n', SMinus)

SPlus (c)
 [0.0678, 0.0856, 0.0099, 0.0894, 0.0895, 0.0283, 0.0663, 0.0226, 0.0342, 0.0833, 0.015, 0.0329, 0.0429, 0.0463, 0.0287, 0.0277, 0.0721, 0.0621, 0.0908, 0.038, 0.0493, 0.0414, 0.0843, 0.0468, 0.027, 0.0531, 0.0278, 0.0235, 0.0377, 0.0211, 0.0414, 0.0212, 0.0625, 0.0448, 0.0883, 0.0063, 0.0893, 0.0426, 0.0133, 0.0832, 0.0419, 0.0438, 0.0122, 0.055, 0.0318, 0.0422, 0.0328, 0.0358, 0.0878, 0.0837, 0.0875, 0.0641, 0.0531, 0.0417, 0.0416, 0.0648, 0.083, 0.0867, 0.0449, 0.0894, 0.052, 0.0648, 0.0871, 0.0445, 0.0415, 0.0692, 0.0307, 0.0512, 0.0221, 0.0419, 0.0314, 0.0447, 0.0372, 0.0673, 0.0205, 0.0651, 0.0458, 0.0188, 0.0834]
SMinus (c)
 [0.0233, 0.0165, 0.0875, 0.0044, 0.004, 0.0649, 0.0255, 0.0685, 0.0631, 0.0301, 0.086, 0.083, 0.0493, 0.0449, 0.0834, 0.0651, 0.0208, 0.0425, 0.0007, 0.0625, 0.0429, 0.0561, 0.0223, 0.0445, 0.0836, 0.0418, 0.0651, 0.0677, 0.0829, 0.0707, 0.0622, 0.0705, 0.0371, 0.0463, 0.0075, 0.0887, 0.0047, 0.0499, 0.0864, 0.0311, 0.0521, 0.0477, 0.0868, 0.0415, 

In [40]:
# Step 5 => calculating performance score
pi = []
for index in range(0, row):
    pi.append(round(SMinus[index] / (SMinus[index] + SPlus[index]), 4))
    
score = pd.DataFrame(pi)
score.columns =['score']
# should only increase if number of rows increase
print('Performance Score (c)\n', pi)

Performance Score (c)
 [0.2558, 0.1616, 0.8984, 0.0469, 0.0428, 0.6964, 0.2778, 0.7519, 0.6485, 0.2654, 0.8515, 0.7161, 0.5347, 0.4923, 0.744, 0.7015, 0.2239, 0.4063, 0.0077, 0.6219, 0.4653, 0.5754, 0.2092, 0.4874, 0.7559, 0.4405, 0.7008, 0.7423, 0.6874, 0.7702, 0.6004, 0.7688, 0.3725, 0.5082, 0.0783, 0.9337, 0.05, 0.5395, 0.8666, 0.2721, 0.5543, 0.5213, 0.8768, 0.4301, 0.667, 0.5958, 0.659, 0.6984, 0.093, 0.2398, 0.1016, 0.3203, 0.4399, 0.5987, 0.5635, 0.3032, 0.2882, 0.1234, 0.5071, 0.0449, 0.4468, 0.3047, 0.1139, 0.5121, 0.5668, 0.2412, 0.6758, 0.4518, 0.7574, 0.5543, 0.6702, 0.5093, 0.6273, 0.2621, 0.8051, 0.2985, 0.4973, 0.8191, 0.2534]


In [41]:
#find maximum pi value 
max_value = max(pi)

#we need index information for maximum pi value 
max_index = pi.index(max_value)

#print the best workshop 
workshop[max_index]

'Bonnet bengkel Surabaya'

In [42]:
#create result dataset
result = pd.concat([data,normalized,weighted,plus_impact,min_impact,score], axis=1)

In [43]:
#short values by score, and adding column rank
final_result = result.sort_values('score', ascending=False)
final_result['rank'] = range(1, 1+len(final_result))

In [44]:
final_result.to_excel('final_result.xlsx')

In [45]:
final_result.head(40)

index                                      workshop_name  \
35     35                            Bonnet bengkel Surabaya   
2       2                            bengkel Gunawangsa MERR   
42     42                    News Front One bengkel Surabaya   
38     38                       Choice City bengkel Surabaya   
10     10                                Grace Setia bengkel   
77     77  OYO 1086 2oscar Near RSUD dr. Soetomo Kota Sur...   
74     74                        bengkel Jawa and Residences   
29     29                               favebengkel Sidoarjo   
31     31                             Grand Surabaya bengkel   
68     68                   Novotel Surabaya bengkel & Suite   
24     24                      Swiss-Belinn Airport Surabaya   
7       7                                      GreenHaus Inn   
14     14                           Maumu bengkel and Lounge   
27     27                                    bengkel Shabine   
11     11                         Cleo bengkel Basuki Rahmat   
15     15                   Luminor bengkel Airport Sidoarjo   
26     26              bengkel Sulawesi Gorontalo - Surabaya   
47     47                   favebengkel Graha Agung Surabaya   
5       5                                    bengkel Permata   
28     28                 Citra Suites Raya Bratang Binangun   
66     66                    ibis budget Surabaya Diponegoro   
70     70                          OYO 1330 bengkel Cahaya 3   
44     44                          Gunawangsa Manyar bengkel   
46     46                     bengkel Ciputra World Surabaya   
8       8                                 bengkel Omah Ampel   
72     72           OYO Flagship 910 Menara Rungkut Surabaya   
19     19                   MaxOnebengkels at Tidar Surabaya   
30     30                    Namira Syariah Surabaya bengkel   
53     53                            Yello bengkel Jemursari   
45     45                           Midtown bengkel Surabaya   
21     21                                       Rock bengkel   
64     64                       Best Western Papilio bengkel   
54     54            Quest bengkel Darmo - Surabaya by ASTON   
69     69                       ibis Budget Surabaya Airport   
40     40                              Cleo bengkel Walikota   
37     37                         bengkel Sulawesi Kertajaya   
12     12                           The Sun bengkel Sidoarjo   
41     41                    BATIQA bengkel Darmo - Surabaya   
63     63                             bengkel Sahid Surabaya   
71     71                         OYO Flagship 1575 Urban 18   

   workshop_province workshop_city  \
35        Jawa Timur      Surabaya   
2         Jawa Timur      Surabaya   
42        Jawa Timur      Surabaya   
38        Jawa Timur      Surabaya   
10        Jawa Timur      Surabaya   
77        Jawa Timur      Surabaya   
74        Jawa Timur      Surabaya   
29        Jawa Timur      Surabaya   
31        Jawa Timur      Surabaya   
68        Jawa Timur      Surabaya   
24        Jawa Timur      Surabaya   
7         Jawa Timur      Surabaya   
14        Jawa Timur      Surabaya   
27        Jawa Timur      Surabaya   
11        Jawa Timur      Surabaya   
15        Jawa Timur      Surabaya   
26        Jawa Timur      Surabaya   
47        Jawa Timur      Surabaya   
5         Jawa Timur      Surabaya   
28        Jawa Timur      Surabaya   
66        Jawa Timur      Surabaya   
70        Jawa Timur      Surabaya   
44        Jawa Timur      Surabaya   
46        Jawa Timur      Surabaya   
8         Jawa Timur      Surabaya   
72        Jawa Timur      Surabaya   
19        Jawa Timur      Surabaya   
30        Jawa Timur      Surabaya   
53        Jawa Timur      Surabaya   
45        Jawa Timur      Surabaya   
21        Jawa Timur      Surabaya   
64        Jawa Timur      Surabaya   
54        Jawa Timur      Surabaya   
69        Jawa Timur      Surabaya   
40        Jawa Timur      Surabaya   
37        J

In [216]:
#print recommended workshop
print ('Recomended workshop is ' + final_result.iloc[0,1])

Recomended workshop is Bonnet bengkel Surabaya
